
// This file was generated by [tauri-specta](https://github.com/oscartbeaumont/tauri-specta). Do not edit this file manually.

/** user-defined commands **/


export const commands = {
async createChat(input: CreateChat) : Promise<Result<Chat, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("create_chat", { input }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getChat(id: string) : Promise<Result<Chat | null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_chat", { id }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async listChats(page: number | null, pageSize: number | null) : Promise<Result<PaginatedResult<Chat>, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("list_chats", { page, pageSize }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async updateChat(id: string, updates: ChatUpdate) : Promise<Result<Chat, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("update_chat", { id, updates }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async deleteChat(id: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("delete_chat", { id }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getWorkspaceChats(workspacePath: string) : Promise<Result<Chat[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_workspace_chats", { workspacePath }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getGroupedHistory() : Promise<Result<GroupedHistory, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_grouped_history") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getAssociatedChat(chatId: string) : Promise<Result<Chat | null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_associated_chat", { chatId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getMessages(chatId: string) : Promise<Result<Message[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_messages", { chatId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async addMessage(input: CreateMessage) : Promise<Result<Message, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("add_message", { input }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async sendMessage(chatId: string, agentType: string, content: string, files: FileAttachment[] | null, config: AgentConfig) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("send_message", { chatId, agentType, content, files, config }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async stopAgent(chatId: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("stop_agent", { chatId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getAgentStatus(chatId: string) : Promise<Result<AgentStatus, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_agent_status", { chatId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async approvePermission(chatId: string, requestId: string, approved: boolean) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("approve_permission", { chatId, requestId, approved }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async detectAgents() : Promise<Result<DetectedAgent[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("detect_agents") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async listAssistantPlugins() : Promise<Result<AssistantPlugin[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("list_assistant_plugins") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async createAssistantPlugin(input: CreateAssistantPlugin) : Promise<Result<AssistantPlugin, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("create_assistant_plugin", { input }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async updateAssistantPlugin(id: string, updates: AssistantPluginUpdate) : Promise<Result<boolean, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("update_assistant_plugin", { id, updates }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async removeAssistantPlugin(id: string) : Promise<Result<boolean, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("remove_assistant_plugin", { id }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async listChannelPlugins() : Promise<Result<ChannelPlugin[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("list_channel_plugins") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async createChannelPlugin(input: CreateChannelPlugin) : Promise<Result<ChannelPlugin, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("create_channel_plugin", { input }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async updateChannelPlugin(id: string, updates: ChannelPluginUpdate) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("update_channel_plugin", { id, updates }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async deleteChannelPlugin(id: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("delete_channel_plugin", { id }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async validateChannelPluginConfig(pluginType: string, config: string | null) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("validate_channel_plugin_config", { pluginType, config }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async listExtensions() : Promise<Result<Extension[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("list_extensions") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async updateExtension(id: string, updates: ExtensionUpdate) : Promise<Result<boolean, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("update_extension", { id, updates }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getSettings(category: string) : Promise<Result<JsonValue, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_settings", { category }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async updateSettings(category: string, settings: JsonValue) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("update_settings", { category, settings }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async changeLanguage(language: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("change_language", { language }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getDefaultConfig() : Promise<Result<AppConfig, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_default_config") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getGeminiSettings() : Promise<Result<GeminiSettings, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_gemini_settings") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async saveGeminiSettings(settings: GeminiSettings) : Promise<Result<GeminiSettings, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("save_gemini_settings", { settings }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getGoogleAuthStatus() : Promise<Result<GoogleAuthStatus, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_google_auth_status") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async startGoogleAuth(email: string) : Promise<Result<GoogleAuthStatus, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("start_google_auth", { email }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async logoutGoogleAuth() : Promise<Result<GoogleAuthStatus, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("logout_google_auth") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getWebuiSettings() : Promise<Result<WebUiSettings, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_webui_settings") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async saveWebuiSettings(settings: WebUiSettings) : Promise<Result<WebUiSettings, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("save_webui_settings", { settings }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getSystemInfo() : Promise<Result<SystemInfo, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_system_info") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getSystemDirectories() : Promise<Result<SystemDirectories, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_system_directories") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async openDevTools() : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("open_dev_tools") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async setZoomFactor(factor: number) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("set_zoom_factor", { factor }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async logFromFrontend(level: string, message: string) : Promise<void> {
    await TAURI_INVOKE("log_from_frontend", { level, message });
},
async listModelProviders() : Promise<Result<ModelProvider[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("list_model_providers") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async createModelProvider(input: CreateModelProviderInput) : Promise<Result<ModelProvider, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("create_model_provider", { input }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async updateModelProvider(id: string, input: UpdateModelProviderInput) : Promise<Result<ModelProvider, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("update_model_provider", { id, input }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async deleteModelProvider(id: string) : Promise<Result<boolean, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("delete_model_provider", { id }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async upsertProviderModel(providerId: string, name: string, originalName: string | null) : Promise<Result<ModelProvider, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("upsert_provider_model", { providerId, name, originalName }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async deleteProviderModel(providerId: string, modelName: string) : Promise<Result<ModelProvider, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("delete_provider_model", { providerId, modelName }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async setModelProviderEnabled(providerId: string, enabled: boolean) : Promise<Result<ModelProvider, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("set_model_provider_enabled", { providerId, enabled }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async setProviderModelEnabled(providerId: string, modelName: string, enabled: boolean) : Promise<Result<ModelProvider, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("set_provider_model_enabled", { providerId, modelName, enabled }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async setProviderModelProtocol(providerId: string, modelName: string, protocol: string) : Promise<Result<ModelProvider, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("set_provider_model_protocol", { providerId, modelName, protocol }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async runModelHealthCheck(providerId: string, modelName: string) : Promise<Result<ModelHealth, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("run_model_health_check", { providerId, modelName }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async readFile(path: string) : Promise<Result<FileContent, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("read_file", { path }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async writeFile(path: string, content: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("write_file", { path, content }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async listDirectory(path: string, recursive: boolean | null) : Promise<Result<FileEntry[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("list_directory", { path, recursive }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async createZip(paths: string[], output: string) : Promise<Result<string, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("create_zip", { paths, output }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async extractZip(path: string, output: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("extract_zip", { path, output }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async downloadFile(url: string, savePath: string) : Promise<Result<string, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("download_file", { url, savePath }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getFileType(path: string) : Promise<Result<FileTypeInfo, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_file_type", { path }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async listMcpServers() : Promise<Result<McpServer[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("list_mcp_servers") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async createMcpServer(input: CreateMcpServer) : Promise<Result<McpServer, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("create_mcp_server", { input }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async updateMcpServer(id: string, updates: McpServerUpdate) : Promise<Result<McpServer, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("update_mcp_server", { id, updates }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async deleteMcpServer(id: string) : Promise<Result<boolean, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("delete_mcp_server", { id }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async testMcpConnection(id: string) : Promise<Result<string, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("test_mcp_connection", { id }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getImageGenerationSettings() : Promise<Result<ImageGenerationSettings, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_image_generation_settings") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async saveImageGenerationSettings(settings: ImageGenerationSettings) : Promise<Result<ImageGenerationSettings, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("save_image_generation_settings", { settings }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async addCronJob(input: CreateCronJob) : Promise<Result<CronJob, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("add_cron_job", { input }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async listCronJobs() : Promise<Result<CronJob[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("list_cron_jobs") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getCronJob(id: string) : Promise<Result<CronJob, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_cron_job", { id }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async updateCronJob(id: string, updates: CronJobUpdate) : Promise<Result<CronJob, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("update_cron_job", { id, updates }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async removeCronJob(id: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("remove_cron_job", { id }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async startWebui(port: number | null, remote: boolean | null) : Promise<Result<WebUiInfo, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("start_webui", { port, remote }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async stopWebui() : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("stop_webui") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getWebuiStatus() : Promise<Result<WebUiStatus, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_webui_status") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async changeWebuiPassword(newPassword: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("change_webui_password", { newPassword }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async resetWebuiPassword() : Promise<Result<ResetWebUiPasswordResult, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("reset_webui_password") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
}
}

/** user-defined events **/



/** user-defined constants **/



/** user-defined types **/

/**
 * Agent 配置
 */
export type AgentConfig = { agent_type: string; command: string | null; args: string[] | null; env: { [key in string]: string } | null; working_dir: string | null }
/**
 * Agent 运行状态
 */
export type AgentStatus = "idle" | "starting" | "running" | "stopping" | "error" | "disconnected"
/**
 * 应用配置结构
 */
export type AppConfig = { theme: string; language: string; zoom_factor: number; webui_port: number; webui_remote: boolean }
export type AssistantPlugin = { id: string; type: string; name: string; enabled: boolean; config: string | null; status: string; last_connected: number | null; created_at: number; updated_at: number }
export type AssistantPluginUpdate = { name: string | null; enabled: boolean | null; config: string | null; status: string | null }
export type ChannelPlugin = { id: string; type: string; name: string; enabled: boolean; config: string | null; status: string; created_at: number; updated_at: number }
export type ChannelPluginUpdate = { name: string | null; enabled: boolean | null; config: string | null; status: string | null }
/**
 * Chat 对外模型 — 序列化到前端（extra 为 JSON Value）
 */
export type Chat = { id: string; user_id: string | null; name: string; type: string; model: string; agent_type: string; workspace_path: string; status: string; extra: JsonValue; created_at: number; updated_at: number }
export type ChatUpdate = { name: string | null; model: string | null; status: string | null; extra: JsonValue | null }
export type CreateAssistantPlugin = { type: string; name: string; config: string | null }
export type CreateChannelPlugin = { type: string; name: string; config: string | null }
export type CreateChat = { name: string; agent_type: string; model: string | null; workspace_path: string | null; extra: JsonValue | null }
export type CreateCronJob = { name: string; cron_expression: string; agent_type: string; prompt: string; enabled: boolean | null }
export type CreateMcpServer = { name: string; type: string; command: string | null; args: string | null; env: string | null; url: string | null; oauth_config: string | null }
export type CreateMessage = { chat_id: string; msg_id: string | null; type: string | null; role: string; content: string; extra: JsonValue | null }
export type CreateModelProviderInput = { platform: string; name: string; baseUrl: string; apiKey: string; contextLimit: number | null }
export type CronJob = { id: string; name: string; cron_expression: string; chat_id: string | null; agent_type: string; prompt: string; enabled: boolean; last_run: number | null; next_run: number | null; status: string; created_at: number; updated_at: number }
export type CronJobUpdate = { name: string | null; cron_expression: string | null; prompt: string | null; enabled: boolean | null; status: string | null; last_run: number | null; next_run: number | null }
/**
 * 检测到的可用 Agent
 */
export type DetectedAgent = { agent_type: string; name: string; command: string; version: string | null; available: boolean }
export type Extension = { id: string; name: string; version: string; description: string | null; path: string; enabled: boolean; config: string | null; created_at: number; updated_at: number }
export type ExtensionUpdate = { name: string | null; version: string | null; description: string | null; enabled: boolean | null; config: string | null }
/**
 * 文件附件（发送消息时附带）
 */
export type FileAttachment = { path: string; name: string; mime_type: string | null }
export type FileContent = { path: string; content: string; size: number; mime_type: string }
export type FileEntry = { name: string; path: string; is_dir: boolean; size: number; modified: number | null }
export type FileTypeInfo = { path: string; mime_type: string; is_text: boolean; is_image: boolean }
export type GeminiSettings = { authType?: string; proxy?: string; GOOGLE_GEMINI_BASE_URL?: string | null; GOOGLE_CLOUD_PROJECT?: string | null; yoloMode?: boolean; preferredMode?: string }
export type GoogleAuthStatus = { connected: boolean; email: string | null; projectId: string | null }
export type GroupedHistory = { today: Chat[]; yesterday: Chat[]; this_week: Chat[]; this_month: Chat[]; earlier: Chat[] }
export type ImageGenerationSettings = { enabled: boolean; provider_id: string | null; model_name: string | null }
export type JsonValue = null | boolean | number | string | JsonValue[] | { [key in string]: JsonValue }
export type McpServer = { id: string; name: string; type: string; command: string | null; args: string | null; env: string | null; url: string | null; enabled: boolean; oauth_config: string | null; created_at: number; updated_at: number }
export type McpServerUpdate = { name: string | null; command: string | null; args: string | null; env: string | null; url: string | null; enabled: boolean | null; oauth_config: string | null }
/**
 * Message 对外模型
 */
export type Message = { id: string; chat_id: string; msg_id: string; type: string; role: string; content: string; position: number; status: string; extra: JsonValue; created_at: number }
export type ModelHealth = { status: ModelHealthStatus; lastCheck: number | null; latency: number | null; error: string | null }
export type ModelHealthStatus = "unknown" | "healthy" | "unhealthy"
export type ModelProvider = { id: string; platform: string; name: string; baseUrl: string; apiKey: string; model?: string[]; enabled: boolean | null; modelEnabled?: { [key in string]: boolean }; modelProtocols?: { [key in string]: string }; modelHealth?: { [key in string]: ModelHealth }; contextLimit: number | null }
export type PaginatedResult<T> = { items: T[]; total: number; page: number; page_size: number }
export type ResetWebUiPasswordResult = { password: string }
export type SystemDirectories = { cache_dir: string; data_dir: string; log_dir: string }
export type SystemInfo = { os: string; arch: string; version: string }
export type UpdateModelProviderInput = { platform: string; name: string; baseUrl: string; apiKey: string; contextLimit: number | null }
/**
 * WebUI 服务器信息（返回给前端）
 */
export type WebUiInfo = { port: number; remote: boolean; url: string; admin_username: string; initial_password: string | null }
export type WebUiSettings = { enabled: boolean; port: number; remote: boolean }
/**
 * WebUI 服务器状态
 */
export type WebUiStatus = { running: boolean; port: number | null; remote: boolean; admin_username: string; initial_password: string | null }

/** tauri-specta globals **/

import {
	invoke as TAURI_INVOKE,
	Channel as TAURI_CHANNEL,
} from "@tauri-apps/api/core";
import * as TAURI_API_EVENT from "@tauri-apps/api/event";
import { type WebviewWindow as __WebviewWindow__ } from "@tauri-apps/api/webviewWindow";

type __EventObj__<T> = {
	listen: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.listen<T>>;
	once: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.once<T>>;
	emit: null extends T
		? (payload?: T) => ReturnType<typeof TAURI_API_EVENT.emit>
		: (payload: T) => ReturnType<typeof TAURI_API_EVENT.emit>;
};

export type Result<T, E> =
	| { status: "ok"; data: T }
	| { status: "error"; error: E };

function __makeEvents__<T extends Record<string, any>>(
	mappings: Record<keyof T, string>,
) {
	return new Proxy(
		{} as unknown as {
			[K in keyof T]: __EventObj__<T[K]> & {
				(handle: __WebviewWindow__): __EventObj__<T[K]>;
			};
		},
		{
			get: (_, event) => {
				const name = mappings[event as keyof T];

				return new Proxy((() => {}) as any, {
					apply: (_, __, [window]: [__WebviewWindow__]) => ({
						listen: (arg: any) => window.listen(name, arg),
						once: (arg: any) => window.once(name, arg),
						emit: (arg: any) => window.emit(name, arg),
					}),
					get: (_, command: keyof __EventObj__<any>) => {
						switch (command) {
							case "listen":
								return (arg: any) => TAURI_API_EVENT.listen(name, arg);
							case "once":
								return (arg: any) => TAURI_API_EVENT.once(name, arg);
							case "emit":
								return (arg: any) => TAURI_API_EVENT.emit(name, arg);
						}
					},
				});
			},
		},
	);
}
